import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { Header } from '@/components'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className='dark'>
			<body
				className={`${inter.className} bg-background text-foreground min-h-screen`}>
				<Providers>
					<Header />
					{children}
					<footer className='h-20 flex items-center justify-center'>
						<h3 className='text-md text-foreground-500 text-center'>
							Creado por Dionicio Vargas
						</h3>
					</footer>
				</Providers>
			</body>
		</html>
	)
}
